global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Documents;
global using System.Windows.Input;
global using System.Windows.Media;
global using System.Windows.Media.Imaging;
global using Wpf.Ui.Controls;
global using LoggingLib;
global using MessageBox = System.Windows.MessageBox;